services:
  front:
    build:
      context: front
      dockerfile: Dockerfile
      args:
        VITE_API_ENDPOINT: ${API_ENDPOINT}
    image: front-service
    depends_on:
      - rt
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.front.rule=Host(`localhost`)"
      - "traefik.http.services.front.loadbalancer.server.port=80"

  auth:
    build:
      context: auth
      dockerfile: Dockerfile
    image: auth-service
    environment:
      DATABASE_URL: ${DATABASE_URL}
      RABBITMQ_URL: ${RABBITMQ_URL}
    depends_on:
      - postgres
      - rabbitmq
      - redis
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth.rule=Host(`localhost`) && PathPrefix(`${API_ENDPOINT}/auth`)"
      - "traefik.http.services.auth.loadbalancer.server.port=3000"
      - "traefik.http.middlewares.auth-strip-prefix.stripprefix.prefixes=${API_ENDPOINT}"
      - "traefik.http.routers.auth.middlewares=auth-strip-prefix"

  users:
    build:
      context: users-service
      dockerfile: Dockerfile
    image: users-service
    environment:
      DATABASE_URL: ${DATABASE_URL}
      RABBITMQ_URL: ${RABBITMQ_URL}
      API_ENDPOINT: ${API_ENDPOINT}
    depends_on:
      - postgres
      - rabbitmq
      - redis
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.users.rule=Host(`localhost`) && PathRegexp(`${API_ENDPOINT}/users/[0-9]+`)"
      - "traefik.http.services.users.loadbalancer.server.port=3000"
      - "traefik.http.middlewares.users-strip-prefix.stripprefix.prefixes=${API_ENDPOINT}"
      - "traefik.http.routers.users.middlewares=users-strip-prefix"

  posts:
    build:
      context: posts-service
      dockerfile: Dockerfile
    image: posts-service
    environment:
      DATABASE_URL: ${DATABASE_URL}
      RABBITMQ_URL: ${RABBITMQ_URL}
    depends_on:
      - postgres
      - rabbitmq
      - redis
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.posts.rule=Host(`localhost`) && PathPrefix(`${API_ENDPOINT}/posts`)"
      - "traefik.http.services.posts.loadbalancer.server.port=3000"
      - "traefik.http.middlewares.posts-strip-prefix.stripprefix.prefixes=${API_ENDPOINT}"
      - "traefik.http.routers.posts.middlewares=posts-strip-prefix"

  media:
    build:
      context: media-service
      dockerfile: Dockerfile
    image: media-service
    environment:
      DATABASE_URL: ${DATABASE_URL}
      RABBITMQ_URL: ${RABBITMQ_URL}
      MINIO_ENDPOINT: ${MINIO_ENDPOINT}
      MINIO_PORT: ${MINIO_PORT}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_BUCKET: ${MINIO_BUCKET}
      MINIO_USE_SSL: ${MINIO_USE_SSL}
    depends_on:
      - postgres
      - rabbitmq
      - minio
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.media.rule=Host(`localhost`) && PathPrefix(`${API_ENDPOINT}/media`)"
      - "traefik.http.services.media.loadbalancer.server.port=3000"
      - "traefik.http.middlewares.media-strip-prefix.stripprefix.prefixes=${API_ENDPOINT}"
      - "traefik.http.routers.media.middlewares=media-strip-prefix"

  rt:
    build:
      context: rt-service
      dockerfile: Dockerfile
    image: rt-service
    environment:
      RABBITMQ_URL: ${RABBITMQ_URL}
    depends_on:
      - rabbitmq
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rt.rule=Host(`localhost`) && PathPrefix(`${API_ENDPOINT}/rt`)"
      - "traefik.http.services.rt.loadbalancer.server.port=3000"
      - "traefik.http.middlewares.rt-strip-prefix.stripprefix.prefixes=${API_ENDPOINT}"
      - "traefik.http.routers.rt.middlewares=rt-strip-prefix"

  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d appdb"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis:
    image: redis:latest
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "rabbitmq-diagnostics -q -n rabbit@$(hostname) status || rabbitmqctl status",
        ]
      interval: 10s
      timeout: 5s
      retries: 6
    restart: unless-stopped

  minio:
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test:
        [
          "CMD",
          "sh",
          "-c",
          "curl -sSf http://localhost:9000/minio/health/ready || exit 1",
        ]
      interval: 5s
      timeout: 3s
      retries: 6
    restart: unless-stopped

  traefik:
    image: traefik
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --api.dashboard=true
      - --api.insecure=true
    ports:
      - ${PUBLIC_PORT} # public HTTP
      - "8080:8080" # optional Traefik dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    depends_on:
      - front
      - auth
      - users
      - posts
      - media
      - rt

volumes:
  postgres_data:
  redis_data:
  rabbitmq_data:
  minio_data:
